### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AhrimanSefid** [Mizogg/ETH-ON-ETH-OFF#1]
![image](https://user-images.githubusercontent.com/1332246/144760308-5540cc38-a764-4775-b945-470c8236027a.png)

**Comment by Mizogg** [comment]
Replace free key with your api key from Ethplorer.. Get FREE API KEY from https://ethplorer.io/

![image](https://user-images.githubusercontent.com/88630056/144760483-61b3dd8b-c33c-4494-ace8-de1ec451fec9.png)


https://user-images.githubusercontent.com/88630056/144760516-6bed3451-627a-4250-a0d2-ca649ece5e1d.mp4

**Comment by Mizogg** [comment]
You need to wait about 10 mins after creating then the API keys works

**Comment by AhrimanSefid** [comment]
https://user-images.githubusercontent.com/1332246/144761079-71926d3b-74bb-4e7e-9c88-1d0a2a732bfe.mp4
